#!/bin/bash
# ccbr_fastqscreen_p2_array 0.0.1
# Generated by dx-app-wizard.

# See https://wiki.dnanexus.com/Developer-Portal for tutorials on how
# to modify this file.

main() {
	# Creating /data directory
	mkdir -p /data
	cd /data

	mv /*.tar.gz /data

	mkdir -p $HOME/out/OutTxt
	mkdir -p $HOME/out/OutPng
	mkdir -p $HOME/out/OutHtml

	# Extracting the tar ball
	tar xzvf *.tar.gz

	(>&2 echo "Listing all files in /data")
	(>&2 tree /data)
	(>&2 echo "Done listing")

	echo "Value of InFq: '${InFq[@]}'"

        # The following line(s) use the dx command-line tool to download your file
        # inputs to the local file system using variable names for the filenames. To
        # recover the original filenames, you can use the output of "dx describe
        # "$variable" --name".

	for i in ${!InFq[@]}
	do
		infq=$(dx describe "${InFq[$i]}" --name)
		echo "Downloading: '${InFq[$i]}'"
		dx download "${InFq[$i]}" -o $infq
	done

	(>&2 echo "Listing all files in /data after downloading them")
	(>&2 tree /data)
	(>&2 echo "Done listing")

	cpus=`nproc`
	dx-docker run -v /data/:/data kopardev/ccbr_fastq_screen_0.13.0 fastq_screen --conf `ls *.conf` `ls *.fastq.gz|sort` --threads $cpus --subset 1000000 --aligner bowtie2

	for f in `ls *_screen.*`;do
		g=`echo $f|sed "s/_screen/_db2_screen/g"`
		mv $f $g
	done

	(>&2 echo "Listing all files in /data after running FastQ Screen")
	(>&2 tree /data)
	(>&2 echo "Done listing")

	mv *.txt $HOME/out/OutTxt
	mv *.png $HOME/out/OutPng
	mv *.html $HOME/out/OutHtml

	(>&2 echo "Listing all files in data")
	(>&2 tree $HOME/out)
	(>&2 echo "Done listing")

	dx-upload-all-outputs --parallel

}

