#!/bin/bash
# ccbr_rnaseq_multiqc_report 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://wiki.dnanexus.com/Developer-Portal for tutorials on how
# to modify this file.

main() {

    echo "Value of FastQC_files: '${FastQC_files[@]}'"
    echo "Value of RawFastQC_files: '${RawFastQC_files[@]}'"
    echo "Value of FastqScreenDB1_files: '${FastqScreenDB1_files[@]}'"
    echo "Value of FastqScreenDB2_files: '${FastqScreenDB2_files[@]}'"
    echo "Value of Picard_duplic_files: '${Picard_duplic_files[@]}'"
    echo "Value of Picard_RNASeqMetrics_files: '${Picard_RNASeqMetrics_files[@]}'"
    echo "Value of STAR_final_out_files: '${STAR_final_out_files[@]}'"

    mkdir -p /data
    cd /data

    dx-download-all-inputs --parallel
    dx-docker run -v "$HOME/in":"$HOME/in" -v "/data":"/data" -w "/data" ewels/multiqc:v1.7 multiqc -d -dd 1 $HOME/in

    OutHtml=$(dx upload /data/multiqc_report.html --brief)

    dx-jobutil-add-output OutHtml "$OutHtml" --class=file
}
